window.PORTFOLIO_PROJECTS = [
  {
    id:"ai-portfolio",
    title:"معرض صناعة المحتوى بالذكاء الاصطناعي",
    type:"AI Visual Content",
    categories:["ai","web"],
    featured:true,
    description:"معرض متخصص يوضح سير العمل من تطوير الفكرة وكتابة المحتوى والـPrompts إلى التوليد والتصميم والمونتاج.",
    tags:["AI","Visual Content","Prompting","Video"],
    liveUrl:"https://madardigital.github.io/hafed-ai-portfolio/",
    githubUrl:"https://github.com/madardigital/hafed-ai-portfolio",
    coverText:"AI Visual Content"
  },
  {
    id:"lenora",
    title:"Lenora Marketing Platform",
    type:"Digital Marketing Platform",
    categories:["web","pr"],
    featured:true,
    description:"منصة تسويقية إلكترونية لعلامة عطور وهدايا، تجمع تجربة عرض المنتجات مع المحتوى التسويقي وربط قنوات التواصل.",
    tags:["Web","Digital Marketing","Content Strategy"],
    liveUrl:"https://madardigital.github.io/lenora-marketing-platform/",
    githubUrl:"https://github.com/madardigital/lenora-marketing-platform",
    coverText:"Lenora Marketing Platform"
  },
  {
    id:"arej",
    title:"أريج — منصة تسويقية للعطور",
    type:"Web & Marketing",
    categories:["web","pr"],
    featured:false,
    description:"واجهة عربية تسويقية تعرض المنتجات وتربط تجربة الموقع باستراتيجية المحتوى ووسائل التواصل وقياس الأداء.",
    tags:["Web","UX/UI","Content","Social Media"],
    liveUrl:"https://madardigital.github.io/arej-platform/",
    githubUrl:"https://github.com/madardigital/arej-platform",
    coverText:"أريج"
  },
  {
    id:"munjiz",
    title:"منجز — تطبيق ويب",
    type:"Web Application",
    categories:["web"],
    featured:false,
    description:"مشروع تطبيق ويب حديث منشور عبر GitHub، يضيف بعدًا تطبيقيًا إلى نماذج المواقع والمنصات الرقمية.",
    tags:["Web App","TypeScript","PWA"],
    githubUrl:"https://github.com/madardigital/munjiz",
    coverText:"منجز"
  },
  {
    id:"hajj-health",
    title:"حملة حج صحي — خطة اتصال وتوعية",
    type:"PR Campaign Case Study",
    categories:["pr","reports"],
    featured:true,
    description:"خطة حملة توعوية صحية تتضمن تحليل الموقف والجمهور، أهداف SMART، الرسائل، التكتيكات، الخطة الزمنية ومؤشرات التقييم.",
    tags:["PR Campaign","Audience Analysis","SMART Objectives","KPIs"],
    cover:"https://drive.google.com/thumbnail?id=1yyHwdmM3EnxS9k5huSQjuEl6evaDO37x&sz=w1600",
    previewUrl:"https://drive.google.com/file/d/1yyHwdmM3EnxS9k5huSQjuEl6evaDO37x/preview",
    sourceUrl:"https://drive.google.com/file/d/1yyHwdmM3EnxS9k5huSQjuEl6evaDO37x/view"
  },
  {
    id:"media-indicators",
    title:"مؤشرات الأخبار الصحفية — منطقة مكة",
    type:"Media Analytics & Report",
    categories:["media","reports","pr"],
    featured:true,
    description:"تقرير بصري لرصد المواد الصحفية وتحويلها إلى مؤشرات أداء، توزيع جغرافي، تصنيف موضوعي، جداول تفصيلية وخلاصة تحليلية.",
    tags:["Media Monitoring","KPIs","Data Visualization","PR"],
    cover:"https://drive.google.com/thumbnail?id=1TeIuFKFqTYM0QCiBxfgSwhVo0YbG7T_Z&sz=w1600",
    previewUrl:"https://drive.google.com/file/d/1TeIuFKFqTYM0QCiBxfgSwhVo0YbG7T_Z/preview",
    sourceUrl:"https://drive.google.com/file/d/1TeIuFKFqTYM0QCiBxfgSwhVo0YbG7T_Z/view"
  },
  {
    id:"training-needs",
    title:"تحديد الاحتياجات التدريبية",
    type:"Professional Presentation",
    categories:["presentations"],
    featured:true,
    description:"عرض تدريبي عربي موسع يبني رحلة تعليمية من تشخيص فجوة الأداء إلى جمع الأدلة وترتيب الاحتياجات وبناء الخطة، ضمن أكثر من مئة شريحة منظمة.",
    tags:["Presentation","Training","RTL","Instructional Design"],
    cover:"https://drive.google.com/thumbnail?id=1XfdTPhB_ETX0kOXcXjaQIJLAKUNSxIbE&sz=w1600",
    previewUrl:"https://drive.google.com/file/d/1XfdTPhB_ETX0kOXcXjaQIJLAKUNSxIbE/preview",
    sourceUrl:"https://docs.google.com/presentation/d/1XfdTPhB_ETX0kOXcXjaQIJLAKUNSxIbE/edit"
  },
  {
    id:"cultural-identity-research",
    title:"التواصل الاجتماعي والهوية الثقافية",
    type:"Research Plan",
    categories:["research"],
    featured:false,
    description:"خطة بحث إعلامية حول دور منصات التواصل الاجتماعي في تعزيز الهوية الثقافية لدى الشباب السعودي، تشمل المشكلة والأهمية والأهداف والأسئلة والإطار النظري والدراسات السابقة.",
    tags:["Research","Social Media","Cultural Identity","Media Studies"],
    cover:"https://drive.google.com/thumbnail?id=1l3N2JhvPQlUTekz2ELaS76MQv3YfEBppxGTXbvrMtTY&sz=w1600",
    previewUrl:"https://docs.google.com/document/d/1l3N2JhvPQlUTekz2ELaS76MQv3YfEBppxGTXbvrMtTY/preview",
    sourceUrl:"https://docs.google.com/document/d/1l3N2JhvPQlUTekz2ELaS76MQv3YfEBppxGTXbvrMtTY/edit"
  },
  {
    id:"radiology-plan",
    title:"الخطة التطويرية المقترحة لقسم الأشعة",
    type:"Analytical / Development Report",
    categories:["reports"],
    featured:false,
    description:"نموذج تقرير تطويري يربط مشكلات التشغيل والإجراءات التصحيحية مع خدمات الأشعة وتعليمات الفحوصات ضمن بنية تحليلية وعملية.",
    tags:["Report","Healthcare","Operational Improvement"],
    cover:"https://drive.google.com/thumbnail?id=17mQ1Qd36mGcr3qBpgOAkRWypxX8LyXIg&sz=w1600",
    previewUrl:"https://drive.google.com/file/d/17mQ1Qd36mGcr3qBpgOAkRWypxX8LyXIg/preview",
    sourceUrl:"https://drive.google.com/file/d/17mQ1Qd36mGcr3qBpgOAkRWypxX8LyXIg/view"
  },
  {
    id:"national-day-poster",
    title:"عزنا بطبعنا — بوستر دعوة للمشاركة",
    type:"Poster Design",
    categories:["posters"],
    featured:false,
    description:"بوستر معلوماتي لمسابقة إبداعية بمناسبة اليوم الوطني السعودي، يوضح فكرة الفعالية ومجالات المشاركة وآلية التسجيل.",
    tags:["Poster","Event Communication","Visual Design"],
    cover:"https://drive.google.com/thumbnail?id=17IRhSgU7Tb8G1aCoOqDU9CB1aWcd66dc&sz=w1600",
    previewUrl:"https://drive.google.com/file/d/17IRhSgU7Tb8G1aCoOqDU9CB1aWcd66dc/preview",
    sourceUrl:"https://drive.google.com/file/d/17IRhSgU7Tb8G1aCoOqDU9CB1aWcd66dc/view"
  },
  {
    id:"motion-intro",
    title:"موشن جرافيك تعريفي",
    type:"Motion Graphics / Video",
    categories:["ai"],
    featured:false,
    description:"نموذج فيديو موشن جرافيك تعريفي ضمن أرشيف الأعمال المرئية، متاح للمشاهدة مباشرة من المعرض.",
    tags:["Motion Graphics","Video","Visual Content"],
    cover:"https://drive.google.com/thumbnail?id=1xK-_1545tdOZsb-29TUTuG6cK7FXzQe5&sz=w1600",
    previewUrl:"https://drive.google.com/file/d/1xK-_1545tdOZsb-29TUTuG6cK7FXzQe5/preview",
    sourceUrl:"https://drive.google.com/file/d/1xK-_1545tdOZsb-29TUTuG6cK7FXzQe5/view"
  }
];
