window.PORTFOLIO_PROJECTS = [
  {
    id:"ai-portfolio",
    title:"معرض صناعة المحتوى بالذكاء الاصطناعي",
    type:"AI Visual Content",
    categories:["ai","web"],
    featured:true,
    description:"معرض متخصص يوضح سير العمل من تطوير الفكرة وكتابة المحتوى والـPrompts إلى التوليد والتصميم والمونتاج.",
    tags:["AI","Visual Content","Prompting","Video"],
    liveUrl:"https://madardigital.github.io/hafed-ai-portfolio/",
    githubUrl:"https://github.com/madardigital/hafed-ai-portfolio",
    coverText:"AI Visual Content"
  },
  {
    id:"lenora",
    title:"Lenora Marketing Platform",
    type:"Digital Marketing Platform",
    categories:["web","pr"],
    featured:true,
    description:"منصة تسويقية إلكترونية لعلامة عطور وهدايا، تجمع تجربة عرض المنتجات مع المحتوى التسويقي وربط قنوات التواصل.",
    tags:["Web","Digital Marketing","Content Strategy"],
    liveUrl:"https://madardigital.github.io/lenora-marketing-platform/",
    githubUrl:"https://github.com/madardigital/lenora-marketing-platform",
    coverText:"Lenora Marketing Platform"
  },
  {
    id:"arej",
    title:"أريج — منصة تسويقية للعطور",
    type:"Web & Marketing",
    categories:["web","pr"],
    featured:false,
    description:"واجهة عربية تسويقية تعرض المنتجات وتربط تجربة الموقع باستراتيجية المحتوى ووسائل التواصل وقياس الأداء.",
    tags:["Web","UX/UI","Content","Social Media"],
    liveUrl:"https://madardigital.github.io/arej-platform/",
    githubUrl:"https://github.com/madardigital/arej-platform",
    coverText:"أريج"
  },
  {
    id:"munjiz",
    title:"منجز — تطبيق ويب لإدارة التكليفات",
    type:"Web Application / PWA",
    categories:["web"],
    featured:false,
    description:"تطبيق ويب عربي موجّه للهاتف لتنظيم التكليفات والمهام، مع وضع محلي وإمكانات مزامنة سحابية عند تفعيلها.",
    tags:["Web App","TypeScript","PWA","Mobile-first"],
    liveUrl:"https://madardigital.github.io/munjiz/",
    githubUrl:"https://github.com/madardigital/munjiz",
    coverText:"منجز"
  },
  {
    id:"hajj-health",
    title:"حملة حج صحي — تقرير وخطة اتصال وتوعية",
    type:"PR Campaign / Report",
    categories:["pr","reports"],
    featured:true,
    embedCover:true,
    description:"تقرير حملة توعوية صحية يتضمن تحليل الموقف والجمهور، أهداف SMART، الرسائل، التكتيكات، الخطة الزمنية ومؤشرات التقييم.",
    tags:["Report","PR Campaign","Audience Analysis","SMART Objectives","KPIs"],
    previewUrl:"https://drive.google.com/file/d/1yyHwdmM3EnxS9k5huSQjuEl6evaDO37x/preview",
    sourceUrl:"https://drive.google.com/file/d/1yyHwdmM3EnxS9k5huSQjuEl6evaDO37x/view"
  },
  {
    id:"hajj-health-visual",
    title:"حج صحي — عرض تقديمي بصري",
    type:"Campaign Presentation",
    categories:["presentations","pr"],
    featured:true,
    embedCover:true,
    description:"عرض بصري للحملة يقدّم الإطار العام، تحليل الموقف، الجمهور، الأهداف والرسائل في صيغة شرائح قابلة للتصفح مباشرة.",
    tags:["Presentation","Campaign","Visual Communication","RTL"],
    previewUrl:"https://drive.google.com/file/d/1vQrPM-ox4eomM5IX-AtBNWgXwHMgoIfv/preview",
    sourceUrl:"https://drive.google.com/file/d/1vQrPM-ox4eomM5IX-AtBNWgXwHMgoIfv/view"
  },
  {
    id:"media-indicators",
    title:"مؤشرات الأخبار الصحفية — منطقة مكة",
    type:"Media Analytics, KPI Dashboard & Report",
    categories:["media","reports","pr","infographics"],
    featured:true,
    embedCover:true,
    description:"تقرير بصري يحول الرصد الصحفي إلى لوحة مؤشرات KPIs، توزيع جغرافي ونوعي، جداول ومصفوفات وخلاصة تحليلية؛ ويظهر أيضًا كنموذج لتصور البيانات والإنفوجرافيك التقريري.",
    tags:["Media Monitoring","KPIs","Data Visualization","Infographic","PR"],
    previewUrl:"https://drive.google.com/file/d/1TeIuFKFqTYM0QCiBxfgSwhVo0YbG7T_Z/preview",
    sourceUrl:"https://drive.google.com/file/d/1TeIuFKFqTYM0QCiBxfgSwhVo0YbG7T_Z/view"
  },
  {
    id:"festival-content",
    title:"مهرجان الثقافات والشعوب — صناعة المحتوى الإعلامي",
    type:"Content Strategy & Media Plan",
    categories:["pr","reports"],
    featured:false,
    embedCover:true,
    description:"خطة محتوى رقمية تتضمن الأهداف والجمهور ومحاور المحتوى والمنصات وتقويم النشر وأفكار منشورات وتسويق الحدث رقميًا.",
    tags:["Content Strategy","Social Media","Event Communication","Editorial Planning"],
    previewUrl:"https://drive.google.com/file/d/1BJA92ChHS7Kp4XAU-d0wnpXYYHhUMVLX/preview",
    sourceUrl:"https://drive.google.com/file/d/1BJA92ChHS7Kp4XAU-d0wnpXYYHhUMVLX/view"
  },
  {
    id:"radiology-plan",
    title:"الخطة التطويرية المقترحة لقسم الأشعة",
    type:"Analytical / Development Report",
    categories:["reports"],
    featured:false,
    embedCover:true,
    description:"نموذج تقرير تطويري يربط مشكلات التشغيل والإجراءات التصحيحية مع خدمات الأشعة وتعليمات الفحوصات ضمن بنية تحليلية وعملية.",
    tags:["Report","Healthcare","Operational Improvement"],
    previewUrl:"https://drive.google.com/file/d/17mQ1Qd36mGcr3qBpgOAkRWypxX8LyXIg/preview",
    sourceUrl:"https://drive.google.com/file/d/17mQ1Qd36mGcr3qBpgOAkRWypxX8LyXIg/view"
  },
  {
    id:"achievement-sample",
    title:"ملف إنجاز تدريب ميداني — نموذج منزوعة بياناته",
    type:"Achievement Portfolio",
    categories:["achievement"],
    featured:false,
    sanitizedPreview:true,
    hideSource:true,
    description:"نموذج حقيقي لهيكلة ملف إنجاز تدريب ميداني. حُجبت منه أسماء الطلبة وبياناتهم، مع إبقاء بنية الملف ونوعية المخرجات التي توضح تنظيم الشواهد والمهام والأنشطة.",
    tags:["Achievement File","Field Training","Documentation","Portfolio"],
    previewHtml:`<div style="min-height:520px;background:#f7f5ef;padding:28px;color:#17302f;overflow:auto"><div style="max-width:760px;margin:auto;background:white;border:1px solid #dce3df;border-radius:22px;padding:28px;box-shadow:0 20px 60px rgba(16,42,43,.09)"><p style="color:#8a6239;font-weight:800;margin:0">معاينة منزوعة البيانات الشخصية</p><h3 style="font-size:30px;margin:8px 0 22px">ملف إنجاز التدريب الميداني</h3><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px"><div style="padding:16px;background:#eef4f1;border-radius:14px"><b>نبذة عن جهة التدريب</b><p>تعريف بالجهة، دورها المجتمعي وأهدافها.</p></div><div style="padding:16px;background:#eef4f1;border-radius:14px"><b>الهيكل التنظيمي</b><p>عرض هيكل القسم والارتباطات التنظيمية.</p></div><div style="padding:16px;background:#eef4f1;border-radius:14px"><b>مهام قسم الإعلام</b><p>الأخبار، التقارير، إدارة حسابات التواصل والتغطيات.</p></div><div style="padding:16px;background:#eef4f1;border-radius:14px"><b>الأعمال والشواهد</b><p>أنشطة، أخبار، ورش ومخرجات إعلامية موثقة.</p></div></div><hr style="border:0;border-top:1px solid #e0e5e1;margin:24px 0"><p style="margin:0;color:#64716f">لا تظهر في هذه المعاينة أسماء الطلبة أو الأرقام الجامعية أو أي بيانات حساسة.</p></div></div>`
  },
  {
    id:"research-sample",
    title:"بحث التحول الرقمي في الخدمات الطلابية — معاينة منزوعة البيانات",
    type:"Academic Research",
    categories:["research"],
    featured:false,
    sanitizedPreview:true,
    hideSource:true,
    description:"نموذج بحث أكاديمي منظم حول التحول الرقمي في قطاع الخدمات الطلابية، مع إخفاء بيانات الطالب وإبقاء بنية البحث ومحاوره العلمية.",
    tags:["Research","Digital Transformation","Higher Education","Academic Writing"],
    previewHtml:`<div style="min-height:520px;background:#f7f5ef;padding:28px;overflow:auto"><article style="max-width:760px;margin:auto;background:#fff;border-radius:20px;padding:30px;border:1px solid #dde3df"><small style="color:#8a6239;font-weight:800">ACADEMIC RESEARCH SAMPLE</small><h3 style="font-size:28px;line-height:1.45">التحول الرقمي في قطاع الخدمات الطلابية</h3><p>مشروع بحث وصفي يناقش أثر التحول الرقمي في الخدمات الطلابية والتحديات التقنية والتنظيمية والبشرية.</p><ol style="line-height:2"><li>الإطار العام للبحث: المشكلة، الأسئلة، الأهداف والأهمية.</li><li>الإطار النظري: التحول الرقمي ونماذج قبول التكنولوجيا ونجاح نظم المعلومات.</li><li>الدراسات السابقة والفجوة البحثية.</li><li>منهجية البحث وتحليل التحديات.</li><li>الحلول التقنية والتنظيمية المقترحة.</li><li>النتائج والتوصيات والمراجع.</li></ol><p style="padding:12px;background:#eef4f1;border-radius:12px">تم حذف الاسم والرقم الجامعي من نسخة العرض في Portfolio.</p></article></div>`
  },
  {
    id:"national-day-poster",
    title:"عزنا بطبعنا — بوستر دعوة للمشاركة",
    type:"Poster Design",
    categories:["posters"],
    featured:false,
    embedCover:true,
    description:"بوستر معلوماتي لمسابقة إبداعية بمناسبة اليوم الوطني السعودي، يوضح فكرة الفعالية ومجالات المشاركة وآلية التسجيل.",
    tags:["Poster","Event Communication","Visual Design"],
    previewUrl:"https://drive.google.com/file/d/17IRhSgU7Tb8G1aCoOqDU9CB1aWcd66dc/preview",
    sourceUrl:"https://drive.google.com/file/d/17IRhSgU7Tb8G1aCoOqDU9CB1aWcd66dc/view"
  },
  {
    id:"heart-care-brochure",
    title:"العناية بالقلب — نموذج مطوية/نشرة طبية",
    type:"Brochure / Medical Leaflet",
    categories:["brochures"],
    featured:false,
    sanitizedPreview:true,
    hideSource:true,
    description:"نموذج من أرشيف تصميم المطويات والنشرات الطبية. تعرض نسخة Portfolio البناء التحريري والبصري بعد إزالة بيانات الاتصال والأسماء من النموذج الأصلي.",
    tags:["Brochure","Leaflet","Healthcare","Information Design"],
    previewHtml:`<div style="min-height:520px;padding:24px;background:#e9f4f2;overflow:auto"><div style="max-width:820px;margin:auto;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));background:white;border-radius:18px;overflow:hidden;box-shadow:0 20px 60px rgba(16,42,43,.12)"><section style="padding:24px;background:#1c7776;color:white"><small>نشرة طبية</small><h3 style="font-size:30px;line-height:1.2">العناية بالقلب</h3><p>تقديم أعلى مستوى من الرعاية للمرضى.</p></section><section style="padding:24px"><h4>من نحن</h4><p>محتوى تعريفي حول الرعاية القلبية، أحدث الابتكارات في الفحص التشخيصي والتدخل القلبي وخيارات العلاج.</p><h4>خدمات مختارة</h4><p>خدمات وقائية وتصوير وفحوصات متخصصة.</p></section><section style="padding:24px;background:#f5f8f7"><h4>إرشادات صحية</h4><p><b>01</b> تجنب التدخين للحد من مخاطر الوفاة والعجز التي يمكن الوقاية منها.</p><p><b>02</b> النشاط البدني المنتظم والمحافظة على الوزن المناسب يقللان مخاطر أمراض القلب.</p><p><b>03</b> التعرف المبكر على أعراض النوبة القلبية مهم لطلب الرعاية المناسبة.</p></section></div><p style="text-align:center;color:#61706e;font-size:12px">نسخة Portfolio منزوعة بيانات الاتصال والأسماء.</p></div>`
  },
  {
    id:"motion-intro",
    title:"موشن جرافيك تعريفي",
    type:"Motion Graphics / Video",
    categories:["ai"],
    featured:false,
    embedCover:true,
    description:"نموذج فيديو موشن جرافيك تعريفي ضمن أرشيف الأعمال المرئية، متاح للمشاهدة مباشرة من المعرض.",
    tags:["Motion Graphics","Video","Visual Content"],
    previewUrl:"https://drive.google.com/file/d/1xK-_1545tdOZsb-29TUTuG6cK7FXzQe5/preview",
    sourceUrl:"https://drive.google.com/file/d/1xK-_1545tdOZsb-29TUTuG6cK7FXzQe5/view"
  }
];
